export const API_ENDPOINTS = {
  ACCOUNTS: '/accounts',
  TRANSACTIONS: '/transactions',
  LOGIN: '/auth/login',
  REGISTER: '/auth/register',
  REFRESH: '/auth/refresh',
  CSRF: '/auth/csrf',
  SUBSCRIPTIONS: '/subscriptions',
  SUBSCRIPTION_UPGRADE: '/subscriptions/upgrade',
  SUBSCRIPTION_CANCEL: '/subscriptions/cancel',
  SUBSCRIPTION_PLANS: '/subscriptions/plans',
  GROUPS: '/groups',
  GROUP_MEMBERS: (groupId: string) => `/groups/${groupId}/members/`,
  GROUP_EXPENSES: (groupId: string) => `/groups/${groupId}/expenses`,
  GROUP_SETTLEMENTS: (groupId: string) => `/groups/${groupId}/settlements`,
  GROUP_BALANCES: (groupId: string) => `/groups/${groupId}/balances`,
  GROUP_HISTORY: (groupId: string) => `/groups/${groupId}/history`,
  BUDGETS: '/budgets',
  CATEGORIES: '/categories',
  REPORTS: '/reports',
  INVOICES: '/invoices',
  SHARED_EXPENSES: '/shared-expenses',
  STATEMENTS: '/statements',
  STATEMENT_UPLOAD: '/statements/upload',
  MONTHLY_BALANCES: '/monthly-balances',
  // Add more endpoints as needed
}; 